### ISSUE TITLE
Getting this error:

### ISSUE THREAD

**Issue by itwasmattgregg** [gucong3000/postcss-syntax#18]
Using stylelint plugin on a vue file but your module is throwing this error. Any thoughts on what it might be?
```
Error: Cannot find module 'postcss-postcss' at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require
(internal/module.js:20:19) at requireSyntax (/Users/floater/.vscode/extensions/shinnn.stylelint
0.36.2/node_modules/postcss-syntax/get-syntax.js:26:19) at getSyntax
(/Users/floater/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-syntax/get
syntax.js:41:10) at LocalFixer.parse (/Users/floater/.vscode/extensions/shinnn.stylelint
0.36.2/node_modules/postcss-syntax/parse-style.js:54:34) at parseStyle
(/Users/floater/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-syntax/parse
style.js:89:39) at styles.sort.forEach.style (/Users/floater/.vscode/extensions/shinnn.stylelint
0.36.2/node_modules/postcss-syntax/parse-style.js:104:17) at Array.forEach (native)
```

**Comment by gucong3000** [comment]
```vue
<style lang="postcss">
</style>
```
Just rewrite this code as:
```vue
<style lang="css">
</style>
```

**Comment by itwasmattgregg** [comment]
That gets rid of the error and linting is now happening but it doesn't appear to be working right with postcss-nested. I have my webpack set up similar to the Vue docs you linked. I'm also using Vetur if that makes a difference.

**Comment by gucong3000** [comment]
Solved in this [PR](https://github.com/gucong3000/postcss-syntax/pull/#19)
